* Implement lookback and a recurrent cell

** TODO Change tensor dimensions inside the model from 4D to 5D
   Dimension should be:
   sample x lookback x lats x lons x channels
   - [ ] Achieve this using generators
   - [X] Start by replacing current setup with generators and test
     sanity and performance

** TODO RNN
   Can be
   - SimpleRNN
   - ESN
   - LSTM
   - GRU

** TODO take another look at the scaling
   Scaling the feedthrough fields with the same scaler as the HR
   fields still gives problems at the boundaries.

* Housekeeping

** DONE data_manager should become a class
   This will make a lot of things more efficient, especially storage
   of interpolators.

** TODO rename main tuning script
   from autoencoder_original to something that makes sense
   
** DONE get rid of residual mode in everything
   I don't think it will work. And at a later stage it might be easier
   to implement again if the code is cleaner.

** DONE get rid of timeindices in ae_model
   not necessary if we can use a lookback

** TODO get rid of old code
   put it somewhere for reference

** TODO implement tests
   - [ ] single epoch, short history
   
